# Generated by Django 5.2.7 on 2025-11-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kanban_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projecttask",
            name="eta",
            field=models.DateField(blank=True, null=True),
        ),
    ]
